### ISSUE TITLE
error in Stock Transfer for multi stores

### ISSUE THREAD

**Issue by ibrahimzakzouk** [nexopos/v3-issues#12] opened 2018-07-09 13:06 UTC
**ibrahim_zakzouk**
user name : ibrahim_zakzouk

**Describe the bug**
I have an issue in Stock Transfer for multi stores , after I make new transfer it doesn’t work !!

1. Go to ' Stock Transfer '
2. Click on ' New Stock Transfer '
3. Click on ' send to "any store"'
4. in product select for ex : SKU '10001'
5. set Quantity to 1 for ex
6. click on 'send The stock'
7. you will see message that all done success but no think is transferred
8. if you go to ' Stock Transfer History ' nothing to see and nothing transferred..

**Expected behavior**
I think that besause no thing is saved in sql database in table stock_transfar

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [ latest version 20-6-2018 ]
 - Gastro [ latest version 4-7-2018 ]
 - PHP version [7.0]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**context**
please respond as far as you can.. Thanks

**Comment by Blair2004** [comment] 2018-07-09 13:10
Thank you for submitting this. We've noticed that your account on Nexo Platform doens't have a licence registered yet. However, we'll investigate on the issue.

**Comment by ibrahimzakzouk** [comment] 2018-07-09 13:12
I had registered a licence ..

**Comment by ibrahimzakzouk** [comment] 2018-07-09 13:23
<img width="1680" alt="screen shot 2018-07-09 at 3 20 32 pm" src="https://user-images.githubusercontent.com/33201203/42453117-0a6385f4-838c-11e8-8734-da4bdeb41e8b.png">

**Comment by ibrahimzakzouk** [comment] 2018-07-09 13:24
done

**Comment by Blair2004** [comment] 2018-07-09 13:34
Thank you, we'll review the issue and let you know as soon as possible.

**Comment by ibrahimzakzouk** [comment] 2018-07-09 13:35
Ok also grouped products not run in multistore when I chose one of them In POS

**Comment by Blair2004** [comment] 2018-07-09 13:36
Please create a dedicated issue for this new on : https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md

**Comment by ibrahimzakzouk** [comment] 2018-07-09 13:41
Ok Thanks I solved the second issue now ..only I need to solve the first issue ..thank you

**Comment by ibrahimzakzouk** [comment] 2018-07-12 16:37
What about the issue ??

**Comment by Blair2004** [comment] 2018-07-13 17:56
We've proceeded to further test but we've not yet found what's going on. We might need to have access to your project.

**Comment by ibrahimzakzouk** [comment] 2018-07-14 02:21
Ok.. no problem

**Comment by ibrahimzakzouk** [comment] 2018-07-16 18:21
??

**Comment by ibrahimzakzouk** [comment] 2018-07-18 12:20
are you here ??

**Comment by Blair2004** [comment] 2018-07-19 17:36
Hi, we're proceeding to another review of the system.

**Comment by Blair2004** [comment] 2018-07-19 17:43
I'm about to transfert from the warehouse to Store A
![image](https://user-images.githubusercontent.com/5265663/42960204-0ab1f28a-8b83-11e8-9028-49ebcebf7028.png)

Here is the store A actual inventory
![image](https://user-images.githubusercontent.com/5265663/42960235-24986db4-8b83-11e8-8d04-3b27fbb2db55.png)

## Transfering 10 quantity of Cheesy Black...
![image](https://user-images.githubusercontent.com/5265663/42960261-39ee7dfc-8b83-11e8-9107-9494640888b9.png)

## Transfert Marked as pending on the warehouse
![image](https://user-images.githubusercontent.com/5265663/42960293-488d55b8-8b83-11e8-9277-08ad53768108.png)

## Marked as well as pending on Store A
![image](https://user-images.githubusercontent.com/5265663/42960319-59d8e800-8b83-11e8-9a22-646289d53f98.png)

## Transfert is approuved from Store A
![image](https://user-images.githubusercontent.com/5265663/42960332-660ab518-8b83-11e8-94da-3f0422060f67.png)

## The item has been created on Store A and the quantity has been supplied
![image](https://user-images.githubusercontent.com/5265663/42960352-753b40d4-8b83-11e8-8810-d2a2a23accb2.png)

## Even from the product history, the stock transfert is shown
![image](https://user-images.githubusercontent.com/5265663/42960382-87e30ee2-8b83-11e8-9129-d907ea48713e.png)

I'm sorry once again, i've proceeded to the test of the system and it's working correctly, please contact any administrator of the community group privately so that we can take a look at your system. For now the issue will be closed, Reason : unable to reproduce.

**Closed by Blair2004** 2018-07-19 17:43 UTC
Labels: help wanted
