### ISSUE TITLE
Daily report not sending!!

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#196] opened 2019-04-14 05:38 UTC
Username : saihati

Describe the bug
In this link in NEXOPOS: /pos/dashboard/stores/7/nexo/settings/reports
It should be send daily report but it dosn't send automatically!!

To Reproduce

Go to 'Store Setting'
Click on 'Reports'
Scroll down to 'Admin Email'
Will NOT send email!!
Expected behavior
I suggest to let send report automatically daily by more configuration. Will be great if it have like detailed report configuration. So I can choose the time (start and end) and select the Format of report like: Detailed or Condensed.

Screenshots

Environment (please complete the following information):

NexoPOS: [e.g. 3.14.2]
PHP version [e.g. 7.1]
MySQL version [5.6]
Devise used (desktop browser Firefox).

Additional context
It is very important to followup the sales for administration.

**Comment by nexopos** [comment] 2019-04-14 05:38
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment] 2019-04-16 09:10
You're changing the formatting, that's why NexoPOS can't understand that. Don't copy the template else where to edit it and repaste it on Github, all the change should be made within the Editor of Github.
Meanwhile, duplicate of https://github.com/nexopos/v3-issues/issues/193

**Closed by Blair2004** 2019-04-16 09:10 UTC
Labels: wrong-issue-format
