### ISSUE TITLE
Kitchen printing issue for v 2.3.103

### ISSUE THREAD

**Issue by alsaihati** [nexopos/v3-issues#344] opened 2020-07-30 15:07 UTC
**Username** : 
saihati

**Describe the bug**
I update Gastro from v 2.3.101 to v 2.3.103. And since I am using 1 printer for 2 different kitchen after update is only print for 1 kitchen. So I downgrade to 101 v then back working and printing.

**Expected behavior**
Kitchen printing as usual for all kitchens

**Comment by nexopos** [comment] 2020-07-30 15:07
<p>Hi, here is a quick recap of your licences on <a href="https://platform.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2018-11-22 18:33:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-08-30 13:48:09</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2019-09-07 12:39:48</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-02-25 09:25:52</td>
                                <td>Not Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-02-25 09:24:52</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-05-25 05:16:34</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>21867974</td>
                                <td>Nexo Print Server</td>
                                <td>2020-07-26 13:30:14</td>
                                <td>Used</td>
                                <td>Expired</td>
                            </tr><tr>
                                <td>20242963</td>
                                <td>Gastro - Restaurant Extension for NexoPOS</td>
                                <td>2021-03-01 06:20:31</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-11-07 01:37:55</td>
                                <td>Not Used</td>
                                <td>Supported</td>
                            </tr><tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2020-12-09 19:53:35</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment] 2020-08-01 13:13
On Gastro 2.3.103 we've changed the way the system handle printed items. In fact, previously, after an order split, there was no way for the system to remember that a specific item has already been printed so paying an order that has been previously sent to the kitchen was printed again. We've changed that behavior by adding a "PRINT_STATUS" to each item so that while the order is being splitter or moved to another table (or even merged), each item keeps their printing status.

As we can see this raises another issue for those using multiple printers to print a single order. We might consider officially ad support for multiple prints. But for not it's not a bug if the old version has what satisfies you, please revert (as you did to it). Keep up on the progress to see if upcoming releases will introduce multiple printers for 1 kitchen as a new feature. 

Thanks.

**Closed as completed by Blair2004** 2020-08-01 13:13 UTC
Labels: supported-licences
