### ISSUE TITLE
Sales Not Showing in cashier Dashboard 

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#85] opened 2018-09-21 08:30 UTC
After finish sale dashboard data not updating 

![index](https://user-images.githubusercontent.com/32275898/45869624-93ff4100-bda6-11e8-8a09-a322e4d532df.jpg)

**Comment by nexopos** [comment] 2018-09-21 08:30
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment] 2018-09-21 09:03
Duplicate of #84

**Closed by Blair2004** 2018-09-21 09:03 UTC
Labels: wrong-issue-format
