### ISSUE TITLE
Three broken links resulting in 404 error. Details below.

### ISSUE THREAD

**Issue by toutavous** [nexopos/v3-issues#14] opened 2018-07-10 15:45 UTC
My Username as created on Nexo Platform is toutavous

-- Bug Description.
1. When you click on the ‘supply receipt’ link on the supply history page. The request returned the following message : Route not found: ”/appfolder/dashboard/nexo/arrivages/delivery_invoice/7/” Code : 404

2. When you click on the edit icon on the ‘Open POS’ page. The request returned the following message : Route not found: ”/appfolder/dashboard/nexo/produits/lists/edit/1/” Code : 404

3. When you click on the ‘edit stock flow’ on the stock flow page. The request returned the following message : Route not found: ”/appfolder/dashboard/nexo/items/supply-history/646692/edit/3/” Code : 404

-- Reproduce Bug
1, Click on "Suppliers List" under Suppliers (Main Menu). Then on the "Options" dropdown menu of each supplier record (row), click on "History". Now click on "Supply Receipt" of any supply record (row). That is the broken link. The supposed supply receipt doesn't appear. Instead, a 404 error results.

2. Click "Open POS" on the main menu. Then click items to be added to the  cart area (to the left) and then simply click on the edit icon by each/any item in the cart. A 404 error results.

3. Click on "Items List" under "Inventory" (Main menu). Then on the "Options" dropdown menu of each item record (row), click on "Supply History". Now click on "Edit Stock Flow" on the "Options" menu of each item' supply history record (row). That is the broken link. The supposed "Edit Stock Flow" page doesn't appear. Instead, a 404 error results.

My environment is:
- NexoPOS: [e.g. 3.12.12]
- PHP version [e.g. 7.1]
- MySQL version [5.6]
- Devise used is Google Chrome on a laptop.
- Modules Enabled for my installation are:
Grocery Crud v1.7.9 Nexo v3.12.12 NexoPOS Updater v1.1 Nexo Premium v2.7.5 Permission Manager v1.4

**Comment by Blair2004** [comment] 2018-07-12 08:22
1 - We've not been able to reproduce this since there is no "History" on the option of the supplies element is available on this screenshot.
![screenshot-nexopos go-2018 07 12-08-58-03](https://user-images.githubusercontent.com/5265663/42620070-d2ac1aa4-85b1-11e8-8597-3427db4903f3.png)

2 - This issue has been detected and fixed, you'll receive a fix on the next update.

3 - Yes, we've been able to reproduce the issue. Thank you, this issue will be fixed as well.
![screenshot-nexopos go-2018 07 12-09-00-41](https://user-images.githubusercontent.com/5265663/42620176-1b7e3a96-85b2-11e8-8ed5-70f3abf5c85d.png)

**Comment by Blair2004** [comment] 2018-07-13 18:44
Thank you we've been able to find that.

**Closed** 2018-07-14 00:46 UTC
Labels: bug, good first issue, help wanted, on going
