### ISSUE TITLE
Printing Issue - kitchen print always on

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#238] opened 2019-08-05 19:54 UTC
**Username** : arauf.qazi@gmail.com
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
So when I create an order and click "To Kitchen", the system prints to both cashier and kitchen. 
Technically it should only print to kitchen printer

Secondly, when I load a HOLD order and want to pay, it prints to both kitchen and cashier. Technically it should print to Cashier only.

Thirdly, when I Create a delivery order, should it not print a delivery receipt? With all the relevant data in it

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment] 2019-08-05 19:54
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by nexopos** [comment] 2019-08-05 21:12
Hi, we've not been able to find the username "arauf" on [Nexo Platform](https://api.nexopos.com).
                    Note that, maybe the issue is not well formatted as well, please consider reading [the tutorial we're writted about](https://nexopos.com/divi-nexopos/how-to-post-an-issue-on-github-for-nexopos-gastro-or-any-nexo-solutions-items/). 
                    Regards.

**Comment by Blair2004** [comment] 2019-08-05 21:45
Alright, we gonna review that. Thanks

**Comment by araufqazi** [comment] 2019-08-05 21:49
Hi,
my nexo platform id is arauf.qazi@gmail.com. I have 2 nexo licenses, 1
gastro license, 1 kiosk license, and 1 NPS license.

Thanks.

**Comment by nexopos** [comment] 2019-08-06 03:25
Alright, no worry.

**Comment by araufqazi** [comment] 2019-08-08 01:00
Hi. Any update on this issue?
To kitchen must only print a receipt to the kitchen printer. There is no need to print on cashier printer. It just wastes more paper for no reason. If we need to print a bill receipt, we can always load the order from "Hold" or "Tables" and print the bill.

**Comment by Blair2004** [comment] 2019-08-08 09:48
Hi, we've made a test and we got only the kitchen receipt when we had the printing unpaid order option set to "no". We would like to check further if you provide the credentials of your system via email : contact@nexopos.com share the link to this issue as well.

**Comment by araufqazi** [comment] 2019-08-08 10:16
Hi,
Mr. Vishal already has my credentials

**Comment by Blair2004** [comment] 2019-08-11 18:59
Well, unfortunately, we cannot help if there is some informations we can't directly get from you. We're close to release the next update and we couldn't ensure the fix for this issue will be included in time.

**Comment by araufqazi** [comment] 2019-08-12 04:33
Hi,
Mr. Vishal already logged into my account and saw the issue for himself.
Even so, i have sent you my login details at contact@nexopos.com.

Thanks.

**Comment by vishalwalia1** [comment] 2019-08-12 15:14
I check all issue mention above and  , technically no issue 

1. If you disable unpaid receipt option and then you send order to kitchen then you only get kitchen receipt print not sale receipt . 
2. for second issue technically you right if we hold a order and later we accept the payment it print both receipt kitchen and sale but ----- think that way it should print kitchen receipt because all order has to ready from kitchen so you will get both receipts . but if you disable the kitchen and then hold the order and take payment later then you will get only get sale receipt because there is no kitchen so no kitchen receipt will print . 
3.Deliver order information issue please see image below , as you can see it does print delivery information. 

![ss](https://user-images.githubusercontent.com/32275898/62876040-b80e9c80-bd41-11e9-9ddc-a2e8c8a2dc9f.jpg)

**Comment by Blair2004** [comment] 2019-08-21 15:14
With the recent change we made on Gastro 2.3.57, we believe it's no more the case. Confirm and reopen the thread if the issue remains.

**Closed by Blair2004** 2019-08-21 15:14 UTC
Labels: on-going, question, wrong-username
